#!/usr/bin/env python3
import argparse,json
from pathlib import Path
r=Path(__file__).resolve().parents[1];p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();schema=json.loads((r/'shared/protocol/v1.schema.json').read_text())
def ts(x):
 if '$ref' in x:return x['$ref'].split('/')[-1]
 if 'enum' in x:return '|'.join(json.dumps(v) for v in x['enum'])
 t=x.get('type')
 if isinstance(t,list):return '|'.join(ts({'type':v}) for v in t)
 if t=='array':return '('+ts(x['items'])+')[]'
 if t=='object':
  if 'properties' not in x:return 'Record<string,'+ts(x.get('additionalProperties',{}))+'>'
  return '{'+''.join(k+('' if k in x.get('required',[]) else '?')+':'+ts(v)+';' for k,v in x['properties'].items())+'}'
 return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(t,'unknown')
outputs={r/'server/internal/permissions/names_gen.go':'// Code generated by scripts/generate-protocol.py. DO NOT EDIT.\npackage permissions\n\nvar Names = []string{\n'+''.join('\t'+json.dumps(p)+',\n' for p in schema['permissions'])+'}\n',r/'client/src/types.ts':'// Generated from shared/protocol/v1.schema.json; run scripts/generate-protocol.py.\n'+''.join('export type '+k+'='+ts(v)+';\n' for k,v in schema['$defs'].items()),r/'server/internal/protocol/version_gen.go':'// Code generated by scripts/generate-protocol.py. DO NOT EDIT.\npackage protocol\n\nconst Version = '+str(schema['protocol_version'])+'\nconst ServerVersion = "'+(r/'SERVER_VERSION').read_text().strip()+'"\n',r/'client/src/version.ts':'// Generated by scripts/generate-protocol.py.\nexport const CLIENT_VERSION="'+(r/'CLIENT_VERSION').read_text().strip()+'",PROTOCOL_VERSION='+str(schema['protocol_version'])+';\n',r/'client/src/permissions.ts':'// Generated by scripts/generate-protocol.py.\nexport const permissionNames='+json.dumps(schema['permissions'])+';\n'}
for file,data in outputs.items():
 if args.check:assert file.read_text()==data,str(file)+' is stale'
 else:file.parent.mkdir(parents=True,exist_ok=True);file.write_text(data)
print('Protocol types OK')
